workflows:
  ios-workflow:
    name: Ice Vault Slot iOS App Store
    environment:
      groups:
        - app_store_credentials
        - certificate_credentials
      vars:
        XCODE_PROJECT: "IceVaultSlot.xcodeproj"
        XCODE_SCHEME: "IceVaultSlot"
        BUNDLE_ID: "com.icevaultapp.game"
        APP_STORE_APPLE_ID: 6778919269
      xcode: latest
      cocoapods: default
    triggering:
      events:
        - push
        - tag
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Set up keychain
        script: |
          keychain initialize
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --platform=IOS --create
      - name: Use system default keychain
        script: |
          keychain add-certificates
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          if [ -n "$APP_STORE_APPLE_ID" ]; then
            agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))
          else
            agvtool new-version -all "${BUILD_NUMBER:-1}"
          fi
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --archive-flags="-destination 'generic/platform=iOS'"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true
